"""quit ClienteJurisdiccion fechas desde y hasta

Revision ID: 0f5cded0fd20
Revises: 2d0fbc80bb91
Create Date: 2025-04-11 17:24:49.812843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5cded0fd20'
down_revision: Union[str, None] = '2d0fbc80bb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente_jurisdiccion', 'fecha_hasta')
    op.drop_column('cliente_jurisdiccion', 'fecha_desde')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente_jurisdiccion', sa.Column('fecha_desde', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('cliente_jurisdiccion', sa.Column('fecha_hasta', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
