"""jurisdiccion.clase.headless + cliente.filtro_fce

Revision ID: 2d0fbc80bb91
Revises: 
Create Date: 2025-04-11 17:13:29.731084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0fbc80bb91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=False),
    sa.Column('client_folder', sa.String(length=255), nullable=False),
    sa.Column('correo_output', sa.String(length=255), nullable=True),
    sa.Column('socio_responsable', sa.String(length=255), nullable=True),
    sa.Column('zip_password', sa.String(length=255), nullable=True),
    sa.Column('rango_consulta_dias', sa.Integer(), nullable=True),
    sa.Column('dias_ejecucion', sa.String(length=255), nullable=True),
    sa.Column('documentacion', sa.Boolean(), nullable=True),
    sa.Column('filtro_fce', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('jurisdicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('clase', sa.String(length=255), nullable=False),
    sa.Column('headless', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdicciones_id'), 'jurisdicciones', ['id'], unique=False)
    op.create_table('usuarios_autorizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('fecha_autorizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_autorizados_id'), 'usuarios_autorizados', ['id'], unique=False)
    op.create_table('cliente_jurisdiccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('jurisdiccion_id', sa.Integer(), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('consultar', sa.Boolean(), nullable=True),
    sa.Column('fecha_desde', sa.String(length=50), nullable=True),
    sa.Column('fecha_hasta', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['jurisdiccion_id'], ['jurisdicciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_jurisdiccion_id'), 'cliente_jurisdiccion', ['id'], unique=False)
    op.create_table('monitoreo_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('iniciado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoreo_bots_id'), 'monitoreo_bots', ['id'], unique=False)
    op.create_table('usuario_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios_autorizados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_cliente_id'), 'usuario_cliente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_cliente_id'), table_name='usuario_cliente')
    op.drop_table('usuario_cliente')
    op.drop_index(op.f('ix_monitoreo_bots_id'), table_name='monitoreo_bots')
    op.drop_table('monitoreo_bots')
    op.drop_index(op.f('ix_cliente_jurisdiccion_id'), table_name='cliente_jurisdiccion')
    op.drop_table('cliente_jurisdiccion')
    op.drop_index(op.f('ix_usuarios_autorizados_id'), table_name='usuarios_autorizados')
    op.drop_table('usuarios_autorizados')
    op.drop_index(op.f('ix_jurisdicciones_id'), table_name='jurisdicciones')
    op.drop_table('jurisdicciones')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
