"""ClienteJurisdiccion.fecha_login_error

Revision ID: 6a38735bc015
Revises: 0f5cded0fd20
Create Date: 2025-04-11 17:35:15.832941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a38735bc015'
down_revision: Union[str, None] = '0f5cded0fd20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente_jurisdiccion', sa.Column('fecha_login_error', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente_jurisdiccion', 'fecha_login_error')
    # ### end Alembic commands ###
